# https://black.readthedocs.io/en/stable/
[tool.black]
line-length = 100
#target-version = ['py38', 'py39']
target-version = ['py310']
include = '\.pyi?$'
extend-exclude = '''
# A regex preceded with ^/ will apply only to files and ctx
# in the root of the project.
^/foo.py  # exclude a file named foo.py in the root of the project (in addition to the defaults)
examples/
'''

# https://mypy.readthedocs.io/en/stable/
# https://pypi.org/project/mypy-extensions/
[tool.mypy]
python_version = "3.10"
ignore_missing_imports = true
scripts_are_modules = true
allow_redefinition = true
disallow_untyped_defs = true
no_implicit_optional = true
warn_no_return = false
show_error_context = true
show_column_numbers = true
show_error_codes = true
color_output = false
pretty = true
exclude = [
    '^setup\.py$',
    '^tmp\.py$',
    '^venv/',
    '^test+\.py$',
    '^conftest\.py$',
    '^tmp/',
    '^examples/'
]
disable_error_code="misc,no-redef,override,union-attr,index,assignment"

[[tool.mypy.overrides]]
module = "tests/*"
disallow_untyped_defs = false

# https://pycqa.github.io/isort/
[tool.isort]
py_version = 310
sections = ['FUTURE', 'STDLIB', 'THIRDPARTY', 'FIRSTPARTY', 'LOCALFOLDER']
profile = "black"
atomic = true
include_trailing_comma = true
line_length = 100
lines_after_imports = 2
lines_between_types = 1
multi_line_output = 3
extend_skip = [".md", ".json"]
known_local_folder = ["deker_local_adapters"]
known_third_party = ["deker_tools"]
extra_standard_library = ["zoneinfo"]
use_parentheses = true

# https://hadialqattan.github.io/pycln/#/README
[tool.pycln]
all = true
diff = true
exclude = "venv/*,.git/*,__pycache__/*,examples/*"
